### ISSUE TITLE
pay-your-bill/ ipad issue

### ISSUE THREAD

**Issue by asif-mahmood-com** [computan/Tyler-Palmer-SunPro-Solar#10]
this block break in ipad 5th

Source URL: https://www.gosunpro.com/pay-your-bill/
|Property | Value|
|------------ | -------------|
| Device | iPad 5th |
| Browser | Tablet_safari |
| Operating System | iOS 11.0 |
| Resolution | 1536 x 2048 px |
| Screen size | 9.7 in - 5.8 x 7.8 in |
| Viewport | 768 x 1024 dp |
| Aspect Ratio | 4 : 3 |

http://prntscr.com/ma2y5l

**Comment by huzaifa-ahmad-com** [comment]
Fixed

**Comment by asif-mahmood-com** [comment]
Done
