### ISSUE TITLE
pay-your-bill/ipad air 2 issue

### ISSUE THREAD

**Issue by asif-mahmood-com** [computan/Tyler-Palmer-SunPro-Solar#11]
looks incorrect in ipad air 2 text is not in its position
| Device | iPad Air 2 |
| Browser | Tablet_safari |
| Operating System | iOS 8.0 |
| Resolution | 1536 x 2048 px |
| Screen size | 9.7 in - 5.8 x 7.8 in |
| Viewport | 768 x 1024 dp |
| Aspect Ratio | 4 : 3 |
http://prntscr.com/ma32eb

**Comment by huzaifa-ahmad-com** [comment]
Fixed

**Comment by asif-mahmood-com** [comment]
Done
