### ISSUE TITLE
pay-your-bill/block break in safari

### ISSUE THREAD

**Issue by asif-mahmood-com** [computan/Tyler-Palmer-SunPro-Solar#9]
in safari Source URL: https://www.gosunpro.com/pay-your-bill/
|Property | Value|
|------------ | -------------|
| Browser | Safari 12.0 |
| Operating System | OS X Mojave |
| Resolution | 1354x646 |

This block breaking
http://prntscr.com/ma2mwg

**Comment by huzaifa-ahmad-com** [comment]
Fixed

**Comment by asif-mahmood-com** [comment]
Done
